/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const UPLOAD         = 'UPLOAD';
export const UPLOAD_LOADING = 'UPLOAD_LOADING';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_ERROR   = 'UPLOAD_ERROR';

export const FETCH_LIST         = 'FETCH_LIST';
export const FETCH_LIST_LOADING = 'FETCH_LIST_LOADING';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_ERROR   = 'FETCH_LIST_ERROR';

export const CHECK_FOLDERS         = 'CHECK_FOLDERS';
export const CHECK_FOLDERS_LOADING = 'CHECK_FOLDERS_LOADING';
export const CHECK_FOLDERS_SUCCESS = 'CHECK_FOLDERS_SUCCESS';
export const CHECK_FOLDERS_ERROR   = 'CHECK_FOLDERS_ERROR';

export const DELETE_FILE         = 'DELETE_FILE';
export const DELETE_FILE_LOADING = 'DELETE_FILE_LOADING';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_ERROR   = 'DELETE_FILE_ERROR';

export const CHECK_INVALID_FILES         = 'CHECK_INVALID_FILES';
export const CHECK_INVALID_FILES_LOADING = 'CHECK_INVALID_FILES_LOADING';
export const CHECK_INVALID_FILES_SUCCESS = 'CHECK_INVALID_FILES_SUCCESS';
export const CHECK_INVALID_FILES_ERROR   = 'CHECK_INVALID_FILES_ERROR';
